name: Allure Reports with history

on:
  #schedule:
  #  - cron: '*/5 * * * *' # every 5 minutes
  push:
    branches-ignore:
      - '!master' # ignore gh-pages
    paths:
      - '!.gitlab-ci.yml'
      - '!allure-template.yml'
      - '**/allure-history.yml'
      - 'allure-report-action/*'

jobs:
  autotests:
    name: Upload allure results to Allure EE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: ./gradlew compileTestJava

      - name: Run Test
        if: always()
        run: ./gradlew test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        #uses: ./allure-report-action
        if: always()
        #id: allure-report
        with:
          allure_results: build/allure-results
          allure_history: allure-history/allure-history
          keep_reports: 5

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history/allure-history